name = "blog"
type = "webpack"
account_id = "21decfb80266c1f3f49a9570a6535c44"

# routing
zone_id = '1115eb69e189f134d9ee5289d715c86e'
route = 'georgeboot.nl/*'
workers_dev = false

[site]
bucket = "./build_production"
entry-point = "workers-site"